### ISSUE TITLE
BACKTRACKING  Questions

### ISSUE THREAD

**Issue by ritweekraj2802** [fdciabdul/Hacktoberfest-Indonesia-2021#126]
I want to add backtracking data structure questions with code in CODE section.
Please assign this to me.
I have participated in HACKTOBERFEST2021
THANK YOU

**Comment by fdciabdul** [comment]
> I want to add backtracking data structure questions with code in CODE section. Please assign this to me. I have participated in HACKTOBERFEST2021 THANK YOU

of course , make PR for that

**Comment by ritweekraj2802** [comment]
@fdciabdul  I have Send PR  .Please accept it If I worked properly.
Thank You.

**Comment by ritweekraj2802** [comment]
@fdciabdul Please accept my PR i send to you

I have participated in HACKTOBERFEST2021 so i need this PR
Thank you
