### ISSUE TITLE
Tanya

### ISSUE THREAD

**Issue by hasobi** [fdciabdul/Hacktoberfest-Indonesia-2021#213]
Halo, saya ingin berkontribusi dengan memberikan dasar-gasar Go, apakah ada guidelines dasar-dasar apa saja yang boleh saya tuliskan atau sejenisnya?

**Comment by fdciabdul** [comment]
> Halo, saya ingin berkontribusi dengan memberikan dasar-gasar Go, apakah ada guidelines dasar-dasar apa saja yang boleh saya tuliskan atau sejenisnya?

tidak ada mas , silahkan PR dengan syarat harus didalam folder code mas 👌
